import { generateId } from '@pos-pymes/shared';
import type {
  ProductInsert,
  UserInsert,
  CategoryInsert,
} from '../schema';

// Seed categories
export const seedCategories: CategoryInsert[] = [
  {
    id: generateId(),
    name: 'Bebidas',
    color: '#3B82F6',
    icon: '🥤',
  },
  {
    id: generateId(),
    name: 'Snacks',
    color: '#F59E0B',
    icon: '🍿',
  },
  {
    id: generateId(),
    name: 'Lácteos',
    color: '#10B981',
    icon: '🥛',
  },
  {
    id: generateId(),
    name: 'Panadería',
    color: '#EF4444',
    icon: '🍞',
  },
  {
    id: generateId(),
    name: 'Limpieza',
    color: '#8B5CF6',
    icon: '🧹',
  },
  {
    id: generateId(),
    name: 'Higiene Personal',
    color: '#EC4899',
    icon: '🧴',
  },
  {
    id: generateId(),
    name: 'Frutas y Verduras',
    color: '#22C55E',
    icon: '🍎',
  },
  {
    id: generateId(),
    name: 'Carnes',
    color: '#DC2626',
    icon: '🥩',
  },
  {
    id: generateId(),
    name: 'Abarrotes',
    color: '#F97316',
    icon: '🍚',
  },
  {
    id: generateId(),
    name: 'Mascotas',
    color: '#06B6D4',
    icon: '🐕',
  },
];

// Sample products
export const seedProducts: ProductInsert[] = [
  // Bebidas
  {
    id: generateId(),
    barcode: '7501000000001',
    name: 'Coca-Cola 600ml',
    brand: 'Coca-Cola',
    unitType: 'piece',
    costPrice: 12.5,
    salePrice: 18.0,
    stockCurrent: 50,
    stockMin: 10,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000002',
    name: 'Agua Natural 1L',
    brand: 'Bonafont',
    unitType: 'piece',
    costPrice: 8.0,
    salePrice: 12.0,
    stockCurrent: 30,
    stockMin: 8,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000003',
    name: 'Jugo de Naranja 1L',
    brand: 'Del Valle',
    unitType: 'piece',
    costPrice: 18.0,
    salePrice: 25.0,
    stockCurrent: 20,
    stockMin: 5,
    isGlobal: false,
  },
  // Snacks
  {
    id: generateId(),
    barcode: '7501000000004',
    name: 'Papas Fritas 100g',
    brand: 'Sabritas',
    unitType: 'piece',
    costPrice: 10.0,
    salePrice: 15.0,
    stockCurrent: 40,
    stockMin: 10,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000005',
    name: 'Galletas Marías',
    brand: 'Marías',
    unitType: 'piece',
    costPrice: 8.5,
    salePrice: 12.0,
    stockCurrent: 25,
    stockMin: 8,
    isGlobal: false,
  },
  // Lácteos
  {
    id: generateId(),
    barcode: '7501000000006',
    name: 'Leche Entera 1L',
    brand: 'Lala',
    unitType: 'piece',
    costPrice: 18.0,
    salePrice: 24.0,
    stockCurrent: 35,
    stockMin: 10,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000007',
    name: 'Yogurt Natural 1L',
    brand: 'Yoplait',
    unitType: 'piece',
    costPrice: 22.0,
    salePrice: 30.0,
    stockCurrent: 15,
    stockMin: 5,
    isGlobal: false,
  },
  // Panadería
  {
    id: generateId(),
    barcode: '7501000000008',
    name: 'Pan de Caja Blanco',
    brand: 'Bimbo',
    unitType: 'piece',
    costPrice: 35.0,
    salePrice: 48.0,
    stockCurrent: 20,
    stockMin: 5,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000009',
    name: 'Pan Dulce (pieza)',
    brand: 'Panadería Local',
    unitType: 'piece',
    costPrice: 3.0,
    salePrice: 5.0,
    stockCurrent: 60,
    stockMin: 15,
    isGlobal: false,
  },
  // Limpieza
  {
    id: generateId(),
    barcode: '7501000000010',
    name: 'Detergente en Polvo 1kg',
    brand: 'Ariel',
    unitType: 'piece',
    costPrice: 45.0,
    salePrice: 65.0,
    stockCurrent: 18,
    stockMin: 5,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000011',
    name: 'Cloro 1L',
    brand: 'Cloralex',
    unitType: 'piece',
    costPrice: 22.0,
    salePrice: 32.0,
    stockCurrent: 25,
    stockMin: 8,
    isGlobal: false,
  },
  // Higiene Personal
  {
    id: generateId(),
    barcode: '7501000000012',
    name: 'Champú 400ml',
    brand: 'Pantene',
    unitType: 'piece',
    costPrice: 55.0,
    salePrice: 78.0,
    stockCurrent: 12,
    stockMin: 4,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000013',
    name: 'Pasta Dental 100ml',
    brand: 'Colgate',
    unitType: 'piece',
    costPrice: 28.0,
    salePrice: 40.0,
    stockCurrent: 30,
    stockMin: 8,
    isGlobal: false,
  },
  // Frutas y Verduras
  {
    id: generateId(),
    barcode: '7501000000014',
    name: 'Manzana (kg)',
    brand: '',
    unitType: 'weight',
    costPrice: 25.0,
    salePrice: 45.0,
    stockCurrent: 15.5,
    stockMin: 5,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000015',
    name: 'Plátano (kg)',
    brand: '',
    unitType: 'weight',
    costPrice: 18.0,
    salePrice: 32.0,
    stockCurrent: 20.0,
    stockMin: 8,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000016',
    name: 'Tomate (kg)',
    brand: '',
    unitType: 'weight',
    costPrice: 20.0,
    salePrice: 38.0,
    stockCurrent: 12.5,
    stockMin: 5,
    isGlobal: false,
  },
  // Carnes
  {
    id: generateId(),
    barcode: '7501000000017',
    name: 'Pechuga de Pollo (kg)',
    brand: '',
    unitType: 'weight',
    costPrice: 85.0,
    salePrice: 120.0,
    stockCurrent: 8.0,
    stockMin: 3,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000018',
    name: 'Carne Molida (kg)',
    brand: '',
    unitType: 'weight',
    costPrice: 95.0,
    salePrice: 135.0,
    stockCurrent: 6.5,
    stockMin: 2,
    isGlobal: false,
  },
  // Abarrotes
  {
    id: generateId(),
    barcode: '7501000000019',
    name: 'Arroz Blanco 1kg',
    brand: 'Rosa',
    unitType: 'piece',
    costPrice: 18.0,
    salePrice: 26.0,
    stockCurrent: 40,
    stockMin: 10,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000020',
    name: 'Frijol Negro 1kg',
    brand: 'La Costeña',
    unitType: 'piece',
    costPrice: 22.0,
    salePrice: 32.0,
    stockCurrent: 35,
    stockMin: 10,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000021',
    name: 'Azúcar 1kg',
    brand: 'Santa Clara',
    unitType: 'piece',
    costPrice: 16.0,
    salePrice: 23.0,
    stockCurrent: 50,
    stockMin: 12,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000022',
    name: 'Sal de Mesa 500g',
    brand: 'Mariana',
    unitType: 'piece',
    costPrice: 8.0,
    salePrice: 12.0,
    stockCurrent: 60,
    stockMin: 15,
    isGlobal: false,
  },
  // Mascotas
  {
    id: generateId(),
    barcode: '7501000000023',
    name: 'Alimento Perro 2kg',
    brand: 'Dog Chow',
    unitType: 'piece',
    costPrice: 85.0,
    salePrice: 120.0,
    stockCurrent: 15,
    stockMin: 5,
    isGlobal: false,
  },
  {
    id: generateId(),
    barcode: '7501000000024',
    name: 'Alimento Gato 1kg',
    brand: 'Whiskas',
    unitType: 'piece',
    costPrice: 65.0,
    salePrice: 95.0,
    stockCurrent: 12,
    stockMin: 4,
    isGlobal: false,
  },
];

// Default admin user
export const seedUsers: UserInsert[] = [
  {
    id: generateId(),
    storeId: 'default-store',
    name: 'Administrador',
    email: 'admin@pos-pymes.local',
    pinHash: '1234', // In production, this should be properly hashed
    role: 'owner',
    permissions: [
      'sales:create',
      'sales:cancel',
      'sales:refund',
      'products:create',
      'products:edit',
      'products:delete',
      'inventory:adjust',
      'cash:open',
      'cash:close',
      'cash:movements',
      'customers:create',
      'customers:edit',
      'customers:delete',
      'credits:create',
      'credits:collect',
      'reports:view',
      'users:manage',
      'settings:manage',
    ],
    active: true,
  },
  {
    id: generateId(),
    storeId: 'default-store',
    name: 'Cajero',
    pinHash: '0000',
    role: 'cashier',
    permissions: [
      'sales:create',
      'cash:open',
      'cash:movements',
      'customers:create',
      'credits:create',
    ],
    active: true,
  },
];
